export default {
  MOBILE_INPUT: 'header__mobile-input',
  NAVIGATION_CONTAINER: 'header__navigation-container',
  NAVIGATION_CONTAINER_ACTIVE: 'header__navigation-container_mobile-active',
  HEADER: 'header',
  HEADER_MOBILE: 'header_mobile',
  OVERLAY: 'overlay',
  OVERLAY_ACTIVE: 'overlay_active',
  NAV_ITEM_DISPLAY_NONE: 'nav__item_display_none',
  HEADER_ARTICLE: 'nav-item-article',
  HEADER_BUTTON_IMAGE: 'header-button-image',
  HEADER_BUTTON: 'header__button',
  HEADER_NAME_PROJECT: 'header__name-project',
  HEADER_NAME_PROJECT_MOBILE: 'header__name-project_mobile',
};
